"""Add all models

Revision ID: 7df9d5936e9b
Revises: b58c4dc79f6a
Create Date: 2025-11-12 23:50:47.599226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df9d5936e9b'
down_revision: Union[str, Sequence[str], None] = 'b58c4dc79f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_id'), 'divisions', ['id'], unique=False)
    op.create_index(op.f('ix_divisions_name'), 'divisions', ['name'], unique=True)
    op.create_table('policy_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('required_parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_policy_templates_category'), 'policy_templates', ['category'], unique=False)
    op.create_index(op.f('ix_policy_templates_id'), 'policy_templates', ['id'], unique=False)
    op.create_table('resource_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(), nullable=False),
    sa.Column('attribute_value', sa.Text(), nullable=True),
    sa.Column('attribute_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_attributes_attribute_name'), 'resource_attributes', ['attribute_name'], unique=False)
    op.create_index(op.f('ix_resource_attributes_id'), 'resource_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_resource_attributes_resource_id'), 'resource_attributes', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_attributes_resource_type'), 'resource_attributes', ['resource_type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('abac_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effect', sa.Enum('allow', 'deny', name='policyeffect'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('department_ids', sa.JSON(), nullable=True),
    sa.Column('division_ids', sa.JSON(), nullable=True),
    sa.Column('role_requirements', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abac_policies_action'), 'abac_policies', ['action'], unique=False)
    op.create_index(op.f('ix_abac_policies_id'), 'abac_policies', ['id'], unique=False)
    op.create_index(op.f('ix_abac_policies_is_active'), 'abac_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_abac_policies_name'), 'abac_policies', ['name'], unique=True)
    op.create_index(op.f('ix_abac_policies_resource_type'), 'abac_policies', ['resource_type'], unique=False)
    op.create_table('user_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_level', sa.Integer(), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('approval_limit_amount', sa.Integer(), nullable=True),
    sa.Column('can_approve_own_department', sa.Boolean(), nullable=True),
    sa.Column('can_approve_all_departments', sa.Boolean(), nullable=True),
    sa.Column('custom_attributes', sa.JSON(), nullable=True),
    sa.Column('office_location', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_attributes_department_id'), 'user_attributes', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_attributes_division_id'), 'user_attributes', ['division_id'], unique=False)
    op.create_index(op.f('ix_user_attributes_id'), 'user_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_user_attributes_team_id'), 'user_attributes', ['team_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('workflow_graph', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'pending', 'approved', 'rejected', 'completed', 'archived', name='workflowstatus'), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('can_view_roles', sa.JSON(), nullable=True),
    sa.Column('can_edit_roles', sa.JSON(), nullable=True),
    sa.Column('can_use_roles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    op.create_table('abac_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('user_attributes', sa.JSON(), nullable=True),
    sa.Column('resource_attributes', sa.JSON(), nullable=True),
    sa.Column('environment_attributes', sa.JSON(), nullable=True),
    sa.Column('evaluated_policies', sa.JSON(), nullable=True),
    sa.Column('evaluation_time_ms', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['abac_policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abac_access_logs_action'), 'abac_access_logs', ['action'], unique=False)
    op.create_index(op.f('ix_abac_access_logs_created_at'), 'abac_access_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_abac_access_logs_id'), 'abac_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_abac_access_logs_resource_id'), 'abac_access_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_abac_access_logs_resource_type'), 'abac_access_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_abac_access_logs_user_id'), 'abac_access_logs', ['user_id'], unique=False)
    op.create_table('workflow_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.Enum('start', 'approval', 'condition', 'parallel', 'end', 'notification', 'action', name='nodetype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('required_role', sa.String(), nullable=True),
    sa.Column('required_roles', sa.JSON(), nullable=True),
    sa.Column('specific_users', sa.JSON(), nullable=True),
    sa.Column('approval_type', sa.Enum('sequential', 'parallel_all', 'parallel_any', 'parallel_majority', name='approvaltype'), nullable=True),
    sa.Column('required_approvals_count', sa.Integer(), nullable=True),
    sa.Column('condition_field', sa.String(), nullable=True),
    sa.Column('condition_operator', sa.String(), nullable=True),
    sa.Column('condition_value', sa.String(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('escalation_user_id', sa.Integer(), nullable=True),
    sa.Column('escalation_role', sa.String(), nullable=True),
    sa.Column('auto_escalate', sa.Boolean(), nullable=True),
    sa.Column('notification_template', sa.String(), nullable=True),
    sa.Column('custom_action', sa.String(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('next_stage_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['escalation_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['next_stage_id'], ['workflow_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_stages_id'), 'workflow_stages', ['id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('workflow_graph', sa.JSON(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_versions_id'), 'workflow_versions', ['id'], unique=False)
    op.create_table('conditional_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=True),
    sa.Column('condition_label', sa.String(), nullable=True),
    sa.Column('condition_field', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('condition_value', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_stage_id'], ['workflow_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stage_id'], ['workflow_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditional_routes_id'), 'conditional_routes', ['id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('workflow_version', sa.Integer(), nullable=True),
    sa.Column('related_model', sa.String(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'pending', 'approved', 'rejected', 'completed', 'archived', name='workflowstatus'), nullable=True),
    sa.Column('initiated_by', sa.Integer(), nullable=True),
    sa.Column('execution_path', sa.JSON(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_stage_id'], ['workflow_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_id'), 'workflow_instances', ['id'], unique=False)
    op.create_table('stage_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('approve', 'reject', 'comment', 'escalate', 'delegate', name='workflowactiontype'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_approvals_id'), 'stage_approvals', ['id'], unique=False)
    op.create_table('workflow_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('approve', 'reject', 'comment', 'escalate', 'delegate', name='workflowactiontype'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_actions_id'), 'workflow_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_actions_id'), table_name='workflow_actions')
    op.drop_table('workflow_actions')
    op.drop_index(op.f('ix_stage_approvals_id'), table_name='stage_approvals')
    op.drop_table('stage_approvals')
    op.drop_index(op.f('ix_workflow_instances_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_conditional_routes_id'), table_name='conditional_routes')
    op.drop_table('conditional_routes')
    op.drop_index(op.f('ix_workflow_versions_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_stages_id'), table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_abac_access_logs_user_id'), table_name='abac_access_logs')
    op.drop_index(op.f('ix_abac_access_logs_resource_type'), table_name='abac_access_logs')
    op.drop_index(op.f('ix_abac_access_logs_resource_id'), table_name='abac_access_logs')
    op.drop_index(op.f('ix_abac_access_logs_id'), table_name='abac_access_logs')
    op.drop_index(op.f('ix_abac_access_logs_created_at'), table_name='abac_access_logs')
    op.drop_index(op.f('ix_abac_access_logs_action'), table_name='abac_access_logs')
    op.drop_table('abac_access_logs')
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_attributes_team_id'), table_name='user_attributes')
    op.drop_index(op.f('ix_user_attributes_id'), table_name='user_attributes')
    op.drop_index(op.f('ix_user_attributes_division_id'), table_name='user_attributes')
    op.drop_index(op.f('ix_user_attributes_department_id'), table_name='user_attributes')
    op.drop_table('user_attributes')
    op.drop_index(op.f('ix_abac_policies_resource_type'), table_name='abac_policies')
    op.drop_index(op.f('ix_abac_policies_name'), table_name='abac_policies')
    op.drop_index(op.f('ix_abac_policies_is_active'), table_name='abac_policies')
    op.drop_index(op.f('ix_abac_policies_id'), table_name='abac_policies')
    op.drop_index(op.f('ix_abac_policies_action'), table_name='abac_policies')
    op.drop_table('abac_policies')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resource_attributes_resource_type'), table_name='resource_attributes')
    op.drop_index(op.f('ix_resource_attributes_resource_id'), table_name='resource_attributes')
    op.drop_index(op.f('ix_resource_attributes_id'), table_name='resource_attributes')
    op.drop_index(op.f('ix_resource_attributes_attribute_name'), table_name='resource_attributes')
    op.drop_table('resource_attributes')
    op.drop_index(op.f('ix_policy_templates_id'), table_name='policy_templates')
    op.drop_index(op.f('ix_policy_templates_category'), table_name='policy_templates')
    op.drop_table('policy_templates')
    op.drop_index(op.f('ix_divisions_name'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_id'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
